module.exports = function(sequelize, DataTypes) {
    var Burger = sequelize.define("Burger", {
		burger_name: DataTypes.STRING,
        devoured: {type: DataTypes.BOOLEAN, defaultValue: false}
        //id - auto-generated by sequelize
        //date (timestamp) - auto-generated by sequelize
    }, {
        classMethods: {
            associate: function(models) {
                Burger.belongsTo(models.Customer);
            }
        }
    });
    return Burger;
}

// var orm = require('../config/orm.js');

// var burgers = {
// 	selectAll: function(cb) {
// 		orm.selectAll("burgers", function(res) {
// 		  cb(res);
// 		});
// 	},
// 	insertOne: function(cols, vals, cb) {
// 		orm.insertOne("burgers", cols, vals, function(res) {
// 		  cb(res);
// 		});
// 	},
// 	updateOne: function(targetString, stringWithTargetId, cb) {
// 		orm.updateOne("burgers", targetString, stringWithTargetId, function(res) {
// 		  cb(res);
// 		});
// 	},
// }

// // Export the database functions for the controller (burgers_controller.js).
// module.exports = burgers;