module.exports = function(sequelize, DataTypes) {
    var Customer = sequelize.define("Customer", {
		customer_name: DataTypes.STRING,
        burgers_purchased: {type: DataTypes.INTEGER, defaultValue: 0}
        //id - auto-generated by sequelize
        //date (timestamp) - auto-generated by sequelize
	}, {
        classMethods: {
            associate: function(models) {
                Customer.hasMany(models.Burger);
            }
        }
    });
    return Customer;
}